-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

ALTER TABLE IF EXISTS public.team_members DROP CONSTRAINT IF EXISTS team_members_pkey;
ALTER TABLE IF EXISTS public.team_members
    ADD CONSTRAINT team_members_pkey PRIMARY KEY (user_id);

ALTER TABLE IF EXISTS public.event_registrations DROP CONSTRAINT IF EXISTS registrations_user_id_fkey;
ALTER TABLE IF EXISTS public.event_registrations
    ADD CONSTRAINT event_registrations_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.profile (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

COMMENT ON TABLE public.profiles
  IS 'should not be used anymore';


ALTER TABLE IF EXISTS public.team_members DROP CONSTRAINT IF EXISTS team_members_user_id_fkey;
ALTER TABLE IF EXISTS public.team_members
    ADD CONSTRAINT team_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES "public"."profile"("user_id");

ALTER TABLE IF EXISTS public.team_requests DROP CONSTRAINT IF EXISTS team_requests_user_id_fkey;
ALTER TABLE IF EXISTS public.team_requests
    ADD CONSTRAINT team_requests_user_id_fkey FOREIGN KEY (user_id) REFERENCES "public"."profile"("user_id");