name: Build WebApp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install deps
      run: npm ci
    
    - name: Lint files
      run: npm run lint
     
    - name: Build 
      run: npm run build --if-present

    - name: List
      run: ls -a
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: webapp-${{ matrix.runs-on }}
        path: .next
